### ISSUE TITLE
config files via exec -it 

### ISSUE THREAD

**Issue by DJR-FP** [simonkowallik/docker#5]
Can you add bash to the container to allow access to config files via  exec -it ?

**Comment by simonkowallik** [comment]
Try `exec -it <container> /bin/ash` to get a shell within the running container. Alpine Linux uses BusyBox which again ships with `ash` as it is more leightweight than bash.

I'll think about including bash or creating an alias, it's not uncommon to run into this as bash is the defacto standard shell for linux and I had a similar reports before.

**Comment by DJR-FP** [comment]
thanks, that worked a treat, gets me to where I need to be.
