### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by jussi-ryoma** [simonkowallik/docker#6]
When running the build command the following error is shown.

`
   Compiling env_logger v0.5.13
   Compiling docopt v1.1.0
   Compiling tclscan v0.0.1 (/build/tclscan)
error[E0583]: file not found for module tcl
  --> src/lib.rs:20:5
   |
20 | mod tcl;
   |     ^^^
   |
   = help: name the file either tcl.rs or tcl/mod.rs inside the directory "src"

error: aborting due to previous error

For more information about this error, try `rustc --explain E0583`.
error: failed to compile `tclscan v0.0.1 (/build/tclscan)`, intermediate artifacts can be found at `/build/tclscan/target`

Caused by:
  Could not compile `tclscan`.

To learn more, run the command again with --verbose.
cp: cannot stat '/root/.cargo/bin/tclscan': No such file or directory
/compile.sh: line 13: tclscan: command not found`

**Comment by simonkowallik** [comment]
@jussi-ryoma thanks for reporting. I remember that there have been some updates to tclscan which might have lead to this issue but I would need to investigate this to confirm.
Unfortunately I have very little time at the moment, but I will try to look at it in the future.

**Comment by simonkowallik** [comment]
tclscan -> [https://github.com/simonkowallik/irulescan/](https://github.com/simonkowallik/irulescan/)
